INSTALL_DIR = $(DM_DIR)

default:
	@echo Please invoke this makefile using sdssmake. >&2
	@exit 1

all: 

clean :
	@ echo in .
	rm -f PP_Diff* PP_Merge* PP_NEW* *~ core *.bak *.orig *.old .\#* \#*\#

install:
